# Generated by Django 6.1 on 2026-08-24 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(default=0)),
                ('message', models.TextField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.TextField()),
                ('ai_explanation', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly', to='logs.logentry')),
            ],
        ),
    ]
